#!/bin/bash
# Update system packages
yum update -y

sudo su

# install docker
sudo yum update
sudo yum install -y docker
sudo systemctl start docker

# Create a directory for the project
mkdir -p /home/ec2-user/stock-app
cd /home/ec2-user/stock-app

# Pull the stock-app Docker image from Docker Hub or build it locally
docker pull gabecasis/stock-app:2

# Run the stock-app container, exposing Flask on port 5001 and metrics on port 8000
docker run -d -p 5001:5001 -p 8000:8000 gabecasis/stock-app:2
